# Generated by Django 4.2 on 2023-04-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_feedsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='guid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
